version: '3.8'

services:
    front:
      image: web-service-front:with-compose
      build: ./front
      ports:
        - 5000:5000
      
    back:
      image: web-service-back:with-compose
      build: ./back
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Mk917gg
      depends_on:
        - db
        
    redis:
      image: redis

    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: Mk917gg
        
    nginx:
      image: nginx
      restart: unless-stopped
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - back
        - front


