version: "3.8"

services:
  front:
    image: ml-front
    build: ./front
    ports:
      - 3000:3000
  
  back:
    image: ml-back
    build: ./back
    ports:
     - 5000:5000
    volumes:
      - model:/src/model 

    
     
  training:
    image: ml-training
    build: ./training
    volumes:
      - model:/src/model

volumes:
  model:
      


