version: '3.8'

services:
    front:
      image: web-service-front:with-compose
      build: ./front
      ports:
        - 5000:5000
      
    back:
      image: web-service-back:with-compose
      build: ./back
      ports:
        - 8080:8080

